### PR TITLE
O.Enroll update

### PR DESCRIPTION
**Pull request by woodbe**
To address the concern in #100 by @FGUERINGTO

### CODE REVIEW

**Comment by stemotre** [comment]
Is there a good reason to prevent systems allowing a User to authenticate with a previously enrolled biometric template before enrollment from being compatible with this cPP, and to require them to gate enrollment to an alternative auth method from the environment (i.e. not bio)?

**Comment by woodbe** [comment]
Wouldn't that be a "chicken and egg" problem? How can you enroll the biometric without having a biometric? MDF generally points to requiring a password as the primary authentication method and as such requires the entry of that before being able to change any credentials (at least that is how I read it at this point). So while I can see technically allowing the user to use one biometric to enroll another, I don't think it is what the MDF intends.

Maybe @lewyble can provide a comment on that.

**Comment by nils-tekampe** [comment]
Just a short question from my side: When we talk about "enrolment": Does this exclusively mean the initial enrolment of a user or would an update of an already existing template also be covered by this description?

**Comment by woodbe** [comment]
So I would actually think no, we don't, but as far as the MDF has been concerned, all enrolments are the same, so they always require the entry of the password before you can enroll one. From the MDF standpoint today (and at least how Samsung devices work) is that you always need to enter the password (or PIN/pattern if you aren't in a CC-specific configuration) before you can make any biometric changes (i.e. enroll a template, delete one, etc). So I don't necessarily have an issue allowing a biometric authentication to be allowed to provide sufficient authorization to make a change, but this is different from the current interpretation I have seen from the MDF standpoint.

**Comment by stemotre** [comment]
Apple is currently also requiring Passcode entry before any (first/new/update...) bio enrollment. 
But again, I felt this is not necessarily about our technical choices.
I think leaving this open would allow developers to make their own choice. I understand that choice could "go away" if the developer also complies to MDF PP and this latter requires the main User device password entry.

**Comment by stemotre** [comment]
Ok, this sounds good then.

**Comment by BrJu** [comment]
checked with François: ok

**Comment by n-kai** [comment]
We agree with this PR at the meeting on 7th June.

**Pull request merged**
