### PR TITLE
FIA_PAD_EXT

### PR DESCRIPTION
**Pull request by woodbe**
This is a proposed add for FIA_PAD_EXT. This doesn't complete all the linkage to the SPD and such that is needed, but I think it gets the SFR updates that are needed correct based on #416.

### CODE REVIEW

**Comment by woodbe** [comment]
Needs to have tracing to the objectives verified as well as dependency tables.

Review all PAD descriptions to make sure this is mentioned properly (if needed).

**Review by n-kai — APPROVED** [review]
PAD L1 or L2 is not defined in the PPM. The CC requires that any technical terms in SFR should be clearly defined. Text for overview about PAD levels should be created (as proposed in #63 in cPP-toolboxes) and add reference to this text to the PPM. Term PAD L(evel) should also be added to 1.5 Glossary. But such modification should be done after creating an overview about PAD levels.

**Comment by woodbe** [comment]
On looking at this integration again, and now that we are actually making plans for PAD-L3, I think maybe we should adjust how this was written to not have the level specifically tied to the modality. If we separate the PAD level from the modality then it is possible to have any PAD for any modality, but the lab/scheme, who would have to be members (or at least have access to the toolboxes( would know what is or isn't allowed and can enforce the restrictions that way without us needing to update the requirements again if/when we add more levels to more modalities.

At this point I don't see anything higher than PAD-L3 as likely, but if we had a selection for the PAD level (which could include PAD-L3 if we wanted, but knowing that this isn't acceptable at the moment), it should work.

**Comment by woodbe** [comment]
I have made the update and included the PAD-L definition in the glossary

**Pull request merged**
