### PR TITLE
Face toolbox

### PR DESCRIPTION
**Pull request by stemotre**
Complete set of test cases identified uploaded

### CODE REVIEW

**Comment by n-kai** [comment]
@stemotre 
Could you tell me how I can see your toolbox?
I downloaded "Face X-X.rtf" and opened them with WordPad but it's unreadable.

**Comment by stemotre** [comment]
Oh... I used the text editor on Mac. 
Let me check if I can convert them to pure txt files...

Stephanie

**Comment by nils-tekampe** [comment]
I just converted the rtf files to pure text. They should be readable now.

**Comment by nils-tekampe** [comment]
Would it be OK for all of you if I moved this Merge  Request to our other repo?

**Comment by woodbe** [comment]
Yes, please go ahead and make this published in the other repo.

Brian

**Comment by nils-tekampe** [comment]
Moved to https://github.com/biometricITC/cPP-toolboxes/pull/1
Closing this one.

**Pull request closed without merging**
