### PR TITLE
Biometric configuration protection

### PR DESCRIPTION
**Pull request by woodbe**
This is in response to #63 to add protection of TOE configuration data explicitly to OSP.Protection and OE.Protection.

### CODE REVIEW

**Comment by n-kai** [comment]
@woodbe @stemotre will create a new pull request to remove A.management and modify the maping table between assumption and objectives.

**Comment by woodbe** [comment]
I only made a few of the application note numbering changes, but everything needs to be updated as 2 were deleted by removing A. Management (and I didn't update all the ones after that, only the last ones)

**Comment by BrJu** [comment]
Please @n-kai @nils-tekampe have a last look before merging.

**Comment by BrJu** [comment]
Note that application notes numbering will need a new update after App Note 24

**Pull request merged**
