### PR TITLE
updates for FIA_MBV_EXT.1.2

### LINKED ISSUE #306: [NIAP] FIA_MBV_EXT.1.2 application notes
Section 8.2.3, FIA_MBV_EXT.1.2, application note 14: This may be more of a endorsement statement thing, but it seems that the ST author is free to put anything they want into the assignments that essentially deal with how well the TOE works. This is not desirable from a "service-to-our-users" perspective. If two TOEs have a certificate and one TOE complies with NIST recommendations on values and the other does not, do we really expect the user to read in the ST to find these values and then make a determination of goodness? The goal for PPs is setting a clear minimum bar that the community believes is both achievable and provides some value to the end user.

Section 8.2.3, FIA_MBV_EXT.1.2, application note 14, item c: This item has the general problem mentioned earlier of containing "shall" statements even though 1) it's in an application note and 2) the introductory text in the application note says "...the ST author should consider..."

The more important issue is that this item uses the term "target error rates", but that is not defined in the glossary (nor anywhere else in the PP-Module), nor is it defined in the SD. It's unclear what this means, especially when the last sentence says that the SD describes how to objectively evaluate these things that aren't defined anywhere (and in fact, the SD does not do this).

### PR DESCRIPTION
**Pull request by woodbe**
This is to close #306.

This sets minimum values for the FAR/FRR and removes the "target"

### CODE REVIEW

**Review by n-kai — COMMENTED** [review]
According to the NIAP **The goal for PPs is setting a clear minimum bar that the community believes is both achievable and provides some value to the end user**

Is this "a value equal to or less than to 1:1000" acceptable **minimum bar** for NIAP for biometric verification performance?

**Comment by woodbe** [comment]
The MDF currently lists 1:100 as the minimum, though I'm not exactly sure how that works given their SAFAR calculations.

**Comment by n-kai** [comment]
See my comment in #306. It's OK to remove "target" if this term is not used by mobile biometric vendors but I need more time to define **minimum bar**.

**Comment by woodbe** [comment]
I don't really know about the "target". I don't think it is needed as I read the text, having it there or not I don't see a change in the meaning. I don't think it needs to be defined, either, since it is clearly what you are trying to achieve. My concern with adding the definition is that we probably then need to review the full text to see if that should be added in more places vs just removing it in the small number where it is currently shown. I think that is the bigger thing, it's use seemed limited to just this requirement in a few sentences and not in any of the descriptive text at the beginning (or elsewhere).

**Comment by n-kai** [comment]
@woodbe 
I agree to remove "target" (I just wanted to explain why I used the term "target")

**Comment by woodbe** [comment]
Closing as superseded by#336

**Pull request closed without merging**
